name: Preprocess Dataset

on:
  push:
    branches: [ main ]
    paths:
      - "preprocessing/**"
      - ".github/workflows/preprocess.yml"
  workflow_dispatch: {}   # bisa run manual

jobs:
  build-preprocessed-dataset:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
    - uses: actions/checkout@v4

    - name: Set up Python 3.12.7
      uses: actions/setup-python@v5
      with:
        python-version: "3.12.7"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas scikit-learn

    # >>> NEW: siapkan data mentah di runner <<<
    - name: Prepare raw data (download AG News + synthesize interactions)
      run: |
        python - <<'PY'
        import pandas as pd, numpy as np, os
        os.makedirs("namadataset_raw", exist_ok=True)
        URL="https://raw.githubusercontent.com/mhjabreel/CharCnn_Keras/master/data/ag_news_csv/train.csv"
        df = pd.read_csv(URL, header=None, names=["label","title","content"])
        label_map={1:"World",2:"Sports",3:"Business",4:"Sci/Tech"}
        df["category"]=df["label"].map(label_map)
        df["article_id"]=np.arange(1,len(df)+1)
        articles=df.sample(n=min(20000,len(df)),random_state=42)[["article_id","title","content","category"]]
        N_USERS=1000; rng=np.random.default_rng(42)
        cats=articles["category"].unique().tolist()
        cat_to_items={c:articles.loc[articles["category"]==c,"article_id"].to_numpy() for c in cats}
        rows=[]
        for u in range(1,N_USERS+1):
            pref=rng.dirichlet(np.ones(len(cats))); n_int=rng.integers(15,35)
            for _ in range(n_int):
                c=rng.choice(cats,p=pref); item=rng.choice(cat_to_items[c])
                score=0.6+0.4*pref[cats.index(c)]+rng.normal(0,0.05)
                rows.append((u,int(item),float(np.clip(score,0,1))))
        inter=pd.DataFrame(rows,columns=["user_id","article_id","interaction"])
        articles.to_csv("namadataset_raw/articles.csv",index=False)
        inter.to_csv("namadataset_raw/interactions.csv",index=False)
        print("Saved raw:",articles.shape,inter.shape)
        PY

    - name: Debug list files
      run: ls -R

    - name: Run preprocessing CLI
      run: |
        python preprocessing/automate_Dhiaz.py \
          --articles namadataset_raw/articles.csv \
          --inter    namadataset_raw/interactions.csv \
          --out_dir  namadataset_preprocessing

    - name: Upload preprocessed dataset artifact
      uses: actions/upload-artifact@v4
      with:
        name: namadataset_preprocessing
        path: namadataset_preprocessing/**
